out_dir = 'D:/NNData/NNData_0626/pred/' #output directory
inp_fname = 'D:/NNData/NNData_0626/in/inFairSIM'
out_fname = 'D:/NNData/NNData_0626/out/outFairSIM'
limit = 1182 #How many image files we want to train
Nthe = 3
Nphi = 1
div_lr = 'D:/Momin/datasets/LR/'
div_hr = 'D:/Momin/datasets/HR/'
valid_in = 'D:/NNData/NNData_0626/in/inFairSIM'
valid_out = 'D:/NNData/NNData_0626/out/outFairSIM'
pickle_loc = 'D:/NNData/NNData_0626/pickle/'
model_loc = 'D:/NNData/NNData_0626/model/'
pickle_n = 50
valid_limit = 169
use_valid_file = False
div_dataset = False
out_channels = 1
#min_lr = .00001
lr_c = 15000
data_reduced = False
in_out_same_size = True
normalize = True
is_3d = False
convert_to_2d = False
save_model_per_epoch = False
save_model_per_interval = True
interval = 50