out_dir = 'drive/My Drive/Colab Notebooks/pred/' #output directory
inp_fname = 'drive/My Drive/Colab Notebooks/in/inFairSIM'
out_fname = 'drive/My Drive/Colab Notebooks/out/outFairSIM'
limit = 1000 #How many image files we want to train
Nthe = 3
Nphi = 5
div_lr = 'D:/Momin/datasets/LR/'
div_hr = 'D:/Momin/datasets/HR/'
valid_in = 'drive/My Drive/Colab Notebooks/valid/in/inFairSIM'
valid_out = 'drive/My Drive/Colab Notebooks/valid/out/outFairSIM'
valid_limit = 1
use_valid_file = True
div_dataset = False
in_channels = 15
out_channels = 1