out_dir = 'C:/Mominul/Dr. Preza/output/pred' #output directory
inp_fname = 'C:/Mominul/Dr. Preza/input/U2OSActin'
out_fname = 'C:/Mominul/Dr. Preza/output/output/outU2OSActin'
limit = 10 #How many image files we want to train
Nthe = 3
Nphi = 5
div_lr = 'D:/Momin/datasets/LR/'
div_hr = 'D:/Momin/datasets/HR/'
div_dataset = False
in_channels = 15
out_channels = 1